config/routes.rb
Depot::Application.routes.draw do
  devise_for :users

  resources :line_items

  resources :carts

  get "store/index"

  resources :products

  root :to => 'store#index', :as => 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  belongs_to :user
  validates_uniqueness_of :user_id
  
  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end
  
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
  
  def owner
    return user
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController  
  
  load_and_authorize_resource
  
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.jsonl
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = current_cart
    @cart.line_items.each do |item|
      @line_item = LineItem.find_by_id(item.id)
      @line_item.destroy
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy        
#    session[:cart_id] = nils
    @cart = current_cart
    render @cart    
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
#cart_title 
  = current_user.name
  = "Cart"

%table#line_items
  =render(cart.line_items)
  
  %tr#total_line
    %td{:colspan => 2} Total
    %td#total_cell= number_to_currency(cart.total_price)
-if cart.line_items.empty?
  %button#delete_cart{:class => 'btn',:href=>'#', 'data-cart-id' => @cart.id, :disabled => true}Empty Cart
-else   
  #delete_cart{:class => 'btn',:href=>'#', 'data-cart-id' => @cart.id } Empty Cart

app/views/carts/edit.html.haml
%h1 Editing cart

%ul
  - @cart.line_items.each do |item|
    %li.cart_item{:id => item.id}=item.product.title

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %tr
    %th
    %th
    %th

  - @carts.each do |cart|
    %tr
      %td= link_to 'Show', cart
      %td= link_to 'Edit', edit_cart_path(cart)
      %td= link_to 'Destroy', cart, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
=render @cart