config/routes.rb
Depot::Application.routes.draw do
  devise_for :users

  resources :line_items

  resources :carts

  get "store/index"

  resources :products

  root :to => 'store#index', :as => 'store'

end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope :order => 'title'
  has_many :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item
    
  validates_presence_of :title, :description, :image_url
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => true
  validates :image_url, :format => {
    :with => %r{\.(gif|jpg|png|jpeg)$}i,
    :message => 'must be a URL for GIF, JPG, JPEG or PNG image.'
  }
  
  private
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product do |f|
  -if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description, :rows => 6
  .field
    = f.label :image_url
    = f.text_field :image_url
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

app/views/products/_product.html.haml
.product_entry
  %h2.product_title{'data-product-id' => product.id}
    =image_tag product.image_url, 'data-product-id' => product.id, :class => 'images'
    =product.title
    %p
      =sanitize(product.description)
  .price_line
    %button{:id => "add_prod_#{product.id}", :class => "add_to_cart btn btn-primary btn-large", :remote => 'true', 'data-product-id' => product.id }Add to Cart
    %span.price
      = number_to_currency product.price

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
#product_list
	%h1 Listing products

	%table
		-@products.each do |product|
			%tr{:class=>cycle('list_line_odd','list_line_even')}
				%td 
					= image_tag(product.image_url, :class => 'list_image')
				%td{:class => 'list_description'}
					%dl
						%dt 
							= product.title
						%dd 
							= truncate(strip_tags(product.description),
							:length => 80)
				%td{:class => 'list_actions'}
					= link_to 'Show', product 
					%br
					= link_to 'Edit', edit_product_path(product)
					%br
					= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete
					
%br

= link_to 'New product', new_product_path				

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @product.title
%p
  %b Description:
  = @product.description
%p
  %b Image url:
  = @product.image_url
%p
  %b Price:
  = @product.price

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path