config/routes.rb
Depot::Application.routes.draw do
  devise_for :users

  resources :line_items

  resources :carts

  get "store/index"

  resources :products

  root :to => 'store#index', :as => 'store'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  
  def total_price
    product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  load_and_authorize_resource

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:product_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
    render :layout => false
  end

  # POST /line_items
  # POST /line_items.json
  def create    
    @cart = current_cart    
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)    
    @line_item.save    
    reset_session_counter
    render @cart    
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])
    @line_item.update_attributes(params[:line_item])
    @cart = current_cart
    render @cart   
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @cart = current_cart
    @line_item = LineItem.find(params[:id])    
    @line_item.destroy
    render @cart
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.haml
= semantic_form_for @line_item do |f|
  =f.semantic_errors
  =f.inputs do
    = f.input :quantity      
  =f.buttons do
    = f.commit_button :button_html => {:class => 'primary'}

app/views/line_items/_line_item.html.haml
%tr{:class => "line_item_entry", :id =>"#{line_item.product.id}"}
  %td#quantity=line_item.quantity
  %td
    .edit_line_item.modal.hide.fade.in
      .modal-header
        %a{ 'data-dismiss'=>"modal", :href=>"#", :class => "close"}&='×'
        %h3
          =line_item.product.title  
      .modal-body
        =twitter_bootstrap_form_for line_item,:remote => true do |f|
          =f.inputs do
            =f.number_field :quantity
          =f.actions do
            =f.submit 'Save'
            %button#delete_line_item{:class => 'btn',:href=>"#", 'data-dismiss'=>"modal", 'data-line-item-id' => line_item.id} Remove from Cart
            =button_tag  'Cancel', :type => 'reset', :class => 'btn'
                
    %a.edit{ :id => "#{line_item.product.id}", 'data-line-item-id'=> line_item.id, 'data-backdrop' => "true", 'data-controls-modal' => "event-modal", 'data-keyboard' => "true"}#{line_item.product.title}
  %td= number_to_currency(line_item.total_price)

app/views/line_items/index.html.haml
%h1 Listing line_items

%table
  %tr
    %th Product
    %th Cart
    %th
    %th
    %th

  - @line_items.each do |line_item|
    %tr
      %td= line_item.product_id
      %td= line_item.cart_id
      %td= link_to 'Show', line_item
      %td= link_to 'Edit', edit_line_item_path(line_item)
      %td= link_to 'Destroy', line_item, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.haml
%h1 New line_item

= render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @line_item.product_id
%p
  %b Cart:
  = @line_item.cart_id

= link_to 'Edit', edit_line_item_path(@line_item)
\|
= link_to 'Back', line_items_path